apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfpecustomerapi1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Mfpecustomerapi1
  template:
    metadata:
      labels:
        app: Mfpecustomerapi1
    spec:
      containers:
      - name: mfpecustomerapirepos1
        image: anujretailbankingcr.azurecr.io/mfpecustomerapirepos1:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn2

---
apiVersion: v1
kind: Service
metadata:
  name: mfpecustomerapi1
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Mfpecustomerapi1
