apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfpe_customerapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Mfpe_customerapi
  template:
    metadata:
      labels:
        app: Mfpe_customerapi
    spec:
      containers:
      - name: mfpecustomerapirepos
        image: anujretailbankingcr.azurecr.io/mfpecustomerapirepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn2

---
apiVersion: v1
kind: Service
metadata:
  name: mfpe_customerapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Mfpe_customerapi
